### ISSUE TITLE
Open Use of the model

### ISSUE THREAD

**Issue by Siziff** [lattas/avatarme#1]
Greetings, thanks a lot for the article :)
Are you planning to upload your model for use ? It would be interesting to personally try to train the model and see how it will work with less realistic faces.

**Comment by lattas** [comment]
Hi,

Unfortunately the code and models have been commercialized, so we cannot share it. However, if you send us some images, we can send back our results for comparison in academic publications. Also, if you decide to try the implementation, let us know if you have any specific questions.

Regards,
Alexandros
