### ISSUE TITLE
Question about the RealFaceDB

### ISSUE THREAD

**Issue by 07hyx06** [lattas/avatarme#2]
Hi, thanks for sharing the dataset.

Is AvatarMe trained on the RealFaceDB dataset? 
The paper says the original dataset contains 200 subjects, each with 7 expressions. Is RealFaceDB the anonymized version of the original dataset? Does it mean the 512x512 patches in RealFaceDB are sampled from the 200 subjects? What about the diversity of the RealFaceDB dataset, is it the same as the original Light Stage dataset?

**Comment by lattas** [comment]
Hi, yes, AvatarMe is trained on the same dataset. The patches are randomly sampled. They have also been cleaned from patches that show clearly identifiable features, as per the capturing license.

**Comment by 07hyx06** [comment]
Thanks for your reply! Can I ask some more questions?

1) What is the UV topology of the RealFaceDB? I notice that AvatarMe and the ++ version are built upon GANFIT. I checked the GANFIT paper and found that it uses the Large Scale Facial Model (LSFM). Does the RealFaceDB use the UV topology of LSFM? Is the LSFM the same topology as the [Universal_Head_3DMM](https://github.com/steliosploumpis/Universal_Head_3DMM) as I find the FitMe project uses this universal head model?
2) Will the code to balance the dataset's skin tone (mentioned in AvatarMe++ and FitMe) be released?

Thanks in advance.
