### ISSUE TITLE
why it have specual normals and diffuse normals 

### ISSUE THREAD

**Issue by xuexiaoxiaohu** [lattas/AvatarMe#2]
Great works
I don't know why you estimate diffuse normals and specular normals, isn't it have only one normal at a point?

**Comment by lattas** [comment]
Hi @xuexiaoxiaohu ,
many commercial applications and research papers are utilizing only one type of normals, which are calculated from the mesh. However, to properly model and photorealistically render a human face, we need to model both the diffuse and the specular reflection. You can read more at: [Weyrich et al., 2006](https://dl.acm.org/doi/abs/10.1145/1141911.1141987), [Ma et al., 2008](http://www.cs.wm.edu/~ppeers/publications/Ma2007RAS/Ma_EGSR2007_lowres.pdf) or [Ghosh et al., 2011](https://dl.acm.org/citation.cfm?id=2024163).

**Comment by xuexiaoxiaohu** [comment]
Okay and thank you very much



---Original---
