### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by test1230-lab** [lattas/AvatarMe#4]
Will the code ever be released?

**Comment by bes1002t** [comment]
I'm also interested in the source code. I wanna create my own eye glasses frame via 3d printing and need a software that creates a 3d model from my face. this would ensure that the glasses will fit perfectly on my face.

**Comment by lattas** [comment]
@test1230-lab  Currently, there are no plans to release the code and trained models for this version of AvatarMe.

**Comment by lattas** [comment]
@bes1002t As I understand you want to create 3D printed glasses for your self. AvatarMe is focused on appearance, not geometry, and therefore perfectly aligned with your application. You could use any of the available 3DMMs (e.g. [Universal Head 3DMM](https://github.com/steliosploumpis/Universal_Head_3DMM), [Basel Face Model](https://faces.dmi.unibas.ch/bfm/) ) or more easily 3D-scan yourself (e.g. [ScandyPro](https://www.scandy.co/apps/scandy-pro), [Bellus3D](https://www.bellus3d.com/), both commercial).

**Comment by bes1002t** [comment]
@lattas I think I found a good way to achieve what I want: meshroom.
I have to play around a little bit and test how accurate it is, but it has a lot of potential.
