### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by 123456789asdfjkl** [lattas/AvatarMe#6]
Thank you for your great work！May I want to know when the code will be released

**Comment by lattas** [comment]
As described in other closed issues, the code is commercialized and will not be released. Instead, we are releasing the dataset [RealFaceDB](https://github.com/lattas/AvatarMe#public-dataset) . You can use the open source [pix2pixHD](https://github.com/NVIDIA/pix2pixHD), together with the changes described in our paper.
